"""add match_score and best_candidate to unmatched_items

Revision ID: 0e57a3d3a973
Revises: d9b3bf61adc8
Create Date: 2026-03-29 19:43:06.660636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e57a3d3a973'
down_revision: Union[str, None] = 'd9b3bf61adc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unmatched_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('match_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('best_candidate', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unmatched_items', schema=None) as batch_op:
        batch_op.drop_column('best_candidate')
        batch_op.drop_column('match_score')

    # ### end Alembic commands ###
