"""add search_quotas table

Revision ID: 35a602d52e73
Revises: 18f7bb98bb5d
Create Date: 2026-03-28 22:46:30.735620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35a602d52e73'
down_revision: Union[str, None] = '18f7bb98bb5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_quotas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('quota_date', sa.Date(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ip', 'quota_date', name='uq_quota_ip_date'),
    sa.UniqueConstraint('user_id', 'quota_date', name='uq_quota_user_date')
    )
    with op.batch_alter_table('search_quotas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_search_quotas_quota_date'), ['quota_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_search_quotas_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('search_quotas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_search_quotas_user_id'))
        batch_op.drop_index(batch_op.f('ix_search_quotas_quota_date'))

    op.drop_table('search_quotas')
    # ### end Alembic commands ###
