"""add_user_tables

Revision ID: 7f6b58f91a3a
Revises: 0001
Create Date: 2026-03-28 19:42:25.185357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f6b58f91a3a'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('nickname', sa.String(length=50), nullable=True),
    sa.Column('subscription_status', sa.String(length=20), nullable=False),
    sa.Column('subscription_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=100), nullable=True),
    sa.Column('registered_ip', sa.String(length=45), nullable=True),
    sa.Column('registered_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False),
    sa.Column('age_confirmed', sa.Boolean(), nullable=False),
    sa.Column('consent_version', sa.String(length=20), nullable=True),
    sa.Column('preferred_currency', sa.String(length=10), nullable=False),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('oauth_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('provider_user_id', sa.String(length=255), nullable=False),
    sa.Column('linked_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_user_id', name='uq_oauth_provider_uid')
    )
    with op.batch_alter_table('oauth_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_oauth_accounts_user_id'), ['user_id'], unique=False)

    op.create_table('user_favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cigar_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cigar_id'], ['cigars.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'cigar_id', name='uq_favorite_user_cigar')
    )
    with op.batch_alter_table('user_favorites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_favorites_cigar_id'), ['cigar_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_favorites_user_id'), ['user_id'], unique=False)

    op.create_table('user_price_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cigar_id', sa.Integer(), nullable=False),
    sa.Column('target_price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cigar_id'], ['cigars.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_price_alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_price_alerts_cigar_id'), ['cigar_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_price_alerts_user_id'), ['user_id'], unique=False)

    op.create_table('user_view_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cigar_id', sa.Integer(), nullable=False),
    sa.Column('viewed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cigar_id'], ['cigars.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_view_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_view_history_cigar_id'), ['cigar_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_view_history_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_view_history_viewed_at'), ['viewed_at'], unique=False)

    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.drop_index('ix_brands_slug')
        batch_op.create_index(batch_op.f('ix_brands_slug'), ['slug'], unique=True)

    with op.batch_alter_table('cigars', schema=None) as batch_op:
        batch_op.drop_index('ix_cigars_slug')
        batch_op.create_index(batch_op.f('ix_cigars_slug'), ['slug'], unique=True)

    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.drop_index('ix_series_slug')
        batch_op.create_index(batch_op.f('ix_series_slug'), ['slug'], unique=True)

    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.drop_index('ix_sources_slug')
        batch_op.create_index(batch_op.f('ix_sources_slug'), ['slug'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sources_slug'))
        batch_op.create_index('ix_sources_slug', ['slug'], unique=False)

    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_series_slug'))
        batch_op.create_index('ix_series_slug', ['slug'], unique=False)

    with op.batch_alter_table('cigars', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cigars_slug'))
        batch_op.create_index('ix_cigars_slug', ['slug'], unique=False)

    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_brands_slug'))
        batch_op.create_index('ix_brands_slug', ['slug'], unique=False)

    with op.batch_alter_table('user_view_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_view_history_viewed_at'))
        batch_op.drop_index(batch_op.f('ix_user_view_history_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_view_history_cigar_id'))

    op.drop_table('user_view_history')
    with op.batch_alter_table('user_price_alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_price_alerts_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_price_alerts_cigar_id'))

    op.drop_table('user_price_alerts')
    with op.batch_alter_table('user_favorites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_favorites_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_favorites_cigar_id'))

    op.drop_table('user_favorites')
    with op.batch_alter_table('oauth_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oauth_accounts_user_id'))

    op.drop_table('oauth_accounts')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
