"""add alert_type and nullable target_price to user_price_alerts

Revision ID: 84175a68ced8
Revises: 35a602d52e73
Create Date: 2026-03-29 09:48:54.760851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84175a68ced8'
down_revision: Union[str, None] = '35a602d52e73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_price_alerts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alert_type', sa.String(length=10), nullable=False))
        batch_op.alter_column('target_price',
               existing_type=sa.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_price_alerts', schema=None) as batch_op:
        batch_op.alter_column('target_price',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.drop_column('alert_type')

    # ### end Alembic commands ###
