"""add scraper_name_aliases table

Revision ID: ad3004217209
Revises: 0e57a3d3a973
Create Date: 2026-03-29 19:57:44.310097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad3004217209'
down_revision: Union[str, None] = '0e57a3d3a973'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scraper_name_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_slug', sa.String(length=50), nullable=False),
    sa.Column('raw_name', sa.String(length=500), nullable=False),
    sa.Column('cigar_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cigar_id'], ['cigars.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_slug', 'raw_name', name='uq_alias_source_raw')
    )
    with op.batch_alter_table('scraper_name_aliases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scraper_name_aliases_cigar_id'), ['cigar_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scraper_name_aliases_source_slug'), ['source_slug'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scraper_name_aliases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scraper_name_aliases_source_slug'))
        batch_op.drop_index(batch_op.f('ix_scraper_name_aliases_cigar_id'))

    op.drop_table('scraper_name_aliases')
    # ### end Alembic commands ###
