"""add scraper_runs and unmatched_items

Revision ID: d9b3bf61adc8
Revises: 84175a68ced8
Create Date: 2026-03-29 18:13:14.523717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9b3bf61adc8'
down_revision: Union[str, None] = '84175a68ced8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scraper_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_slug', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('items_scraped', sa.Integer(), nullable=False),
    sa.Column('items_matched', sa.Integer(), nullable=False),
    sa.Column('items_unmatched', sa.Integer(), nullable=False),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scraper_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scraper_runs_source_slug'), ['source_slug'], unique=False)

    op.create_table('unmatched_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('source_slug', sa.String(length=50), nullable=False),
    sa.Column('raw_name', sa.String(length=500), nullable=False),
    sa.Column('price_single', sa.Float(), nullable=True),
    sa.Column('price_box', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('product_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['scraper_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('unmatched_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_unmatched_items_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_unmatched_items_source_slug'), ['source_slug'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unmatched_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_unmatched_items_source_slug'))
        batch_op.drop_index(batch_op.f('ix_unmatched_items_run_id'))

    op.drop_table('unmatched_items')
    with op.batch_alter_table('scraper_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scraper_runs_source_slug'))

    op.drop_table('scraper_runs')
    # ### end Alembic commands ###
