"""add edition and parent_cigar_id to cigars

Revision ID: f3bc22bdabfe
Revises: ad3004217209
Create Date: 2026-03-29 21:47:14.364471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3bc22bdabfe'
down_revision: Union[str, None] = 'ad3004217209'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cigars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('edition_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('edition', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('parent_cigar_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_cigars_parent_cigar_id'), ['parent_cigar_id'], unique=False)
        batch_op.create_foreign_key('fk_cigars_parent_cigar_id', 'cigars', ['parent_cigar_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cigars', schema=None) as batch_op:
        batch_op.drop_constraint('fk_cigars_parent_cigar_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_cigars_parent_cigar_id'))
        batch_op.drop_column('parent_cigar_id')
        batch_op.drop_column('edition')
        batch_op.drop_column('edition_type')

    # ### end Alembic commands ###
